server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Carlosho23/ead-config-server-repo
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}


eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost