server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Carlosho23/ead-config-server-repo
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}

ead:
  configServer:
    username: configserver
    password: 'ead123cr'
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost